#!/bin/bash
NAMES=( John Eric Jessica )
NUMBERS=( 1 2 3 )
STRINGS=( "hello world" )
# NumberOfNames devra contenir le nombre total de nom que contient le tableau NAMES en utilisant la variable spécial $#. La variable second_name devra contenir le second nom que contient le tableau NAMES EN UTILISANT l'operat
# eur brackets [].
NumberOfNames=${#NAMES[@]}
second_name=${NAMES[1]}
echo ${NUMBERS[@]}
echo ${STRINGS[@]}
echo "Le nombre total d'élément que contient le tableau NAMES est: $NumberOfNames
echo "Le second élément du tableau NAMES est: $second_name
