#!/bin/bash
# change this variables
NUMBER=16
APPLES=16
KING="LUIZ"
#Les variables ci dessus ont été changé afin que les conditions soit vraie afin que les instructions s'exécute.
if [ $NUMBER -gt 15 ] ; then
  echo 1
fi
if [ $NUMBER -eq $APPLES ] ; then
  echo 2
fi
if [[ ($APPLES -eq 12) || ("$KING" = "LUIZ") ]] ; then
  echo 3
fi
if [[ $(($NUMBER + $APPLES)) -le 32 ]] ; then
  echo 4
fi 
