#!/bin/bash
#écrire la fonction nommé ENGLISH_CALC
ENGLISH_CALC () {
	if [ $2 == PLUS ]; then
	 echo "3 + 5 = $(($1+$3))"
	elif [ $2 == minus ]; then
	echo "5 - 1= $(($1-$3))" 
	elif [ $2 == times ]; then
	echo "4 * 6 = $(($1 * $3))" 
fi
}
ENGLISH_CALC 3 PLUS 5
ENGLISH_CALC 5 minus 1
ENGLISH_CALC 4 times 6 
